# Generated by Django 2.1.4 on 2018-12-10 10:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='machines name')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(default=None, max_length=200, verbose_name='experiment name')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='number')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='scxrd.Machine', verbose_name='diffractometer')),
                ('sum_formula', models.CharField(blank=True, max_length=300)),
                ('measure_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='measurement date')),
                ('submit_date', models.DateField(blank=True, null=True, verbose_name='sample submission date')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='structure results date')),
                ('cif', models.FileField(blank=True, null=True, upload_to='scxrd/cifs', verbose_name='cif file')),
                ('operator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to=settings.AUTH_USER_MODEL, verbose_name='operator')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Solvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='solvents name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='solvents_used',
            field=models.ManyToManyField(blank=True, to='scxrd.Solvent', verbose_name='solvents used'),
        ),
    ]
