# Generated by Django 2.1.3 on 2018-12-02 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(default=None, max_length=200, verbose_name='experiment name')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time of measurement')),
                ('number', models.IntegerField(unique=True, verbose_name='number')),
                ('sum_formula', models.CharField(max_length=300)),
                ('solvents_used', models.IntegerField(choices=[[1, '']], verbose_name='solvents used')),
                ('machine', models.IntegerField(choices=[(1, 'Foo'), (2, 'Bar'), (3, 'APEX')], default='Select Machine', verbose_name='machine used')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='sachines name')),
            ],
        ),
        migrations.CreateModel(
            name='Solvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='solvents name')),
            ],
        ),
    ]
