# Generated by Django 2.1.4 on 2018-12-14 08:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CifFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.FileField(blank=True, null=True, upload_to='cifs')),
                ('sha1', models.CharField(blank=True, max_length=256, null=True)),
                ('filesize', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=250, verbose_name='last name')),
                ('workgroup', models.CharField(blank=True, max_length=250, null=True, verbose_name='work group')),
                ('company', models.CharField(blank=True, max_length=250, null=True, verbose_name='company')),
                ('mail_adress', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(default=None, max_length=200, verbose_name='experiment name')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='number')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='scxrd.Machine', verbose_name='diffractometer')),
                ('sum_formula', models.CharField(blank=True, max_length=300)),
                ('measure_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='measurement date')),
                ('submit_date', models.DateField(blank=True, null=True, verbose_name='sample submission date')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='structure results date')),
                ('cif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cif_file', to='scxrd.CifFile', verbose_name='cif file')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scxrd.Customer')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to=settings.AUTH_USER_MODEL, verbose_name='operator')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='machines name')),
            ],
        ),
        migrations.CreateModel(
            name='Solvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='solvents name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='solvents_used',
            field=models.ManyToManyField(blank=True, to='scxrd.Solvent', verbose_name='solvents used'),
        ),
    ]
