# Generated by Django 2.1.4 on 2018-12-07 20:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scxrd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='solvent',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='date',
        ),
        migrations.AddField(
            model_name='experiment',
            name='measure_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='measurement date'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to=settings.AUTH_USER_MODEL, verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='result_date',
            field=models.DateField(blank=True, null=True, verbose_name='structure results date'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='submit_date',
            field=models.DateField(blank=True, null=True, verbose_name='sample submission date'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='scxrd.Machine', verbose_name='diffractometer'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='number'),
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='solvents_used',
        ),
        migrations.AddField(
            model_name='experiment',
            name='solvents_used',
            field=models.ManyToManyField(blank=True, to='scxrd.Solvent', verbose_name='solvents used'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sum_formula',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=200, verbose_name='machines name'),
        ),
        migrations.AlterField(
            model_name='solvent',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='solvents name'),
        ),
    ]
