# Generated by Django 2.1.5 on 2019-01-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumformula',
            name='cif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sumform', to='scxrd.CifFile'),
        ),
    ]
