# Generated by Django 2.1.7 on 2019-02-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciffile',
            name='diffrn_measurement_specimen_support',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
