# Generated by Django 2.1.4 on 2019-01-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciffile',
            name='database_code_depnum_ccdc_archive',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CCDC number'),
        ),
    ]
