# Generated by Django 2.1.5 on 2019-01-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrystalShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitus', models.CharField(max_length=200, unique=True, verbose_name='crystal shape')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='special_details',
            field=models.TextField(blank=True, default='', null=True, verbose_name='experimental special details'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='crystal_colour',
            field=models.IntegerField(choices=[(0, 'not applicable'), (1, 'colourless'), (2, 'white'), (3, 'black'), (4, 'gray'), (5, 'brown'), (6, 'red'), (7, 'pink'), (8, 'orange'), (9, 'yellow'), (10, 'green'), (11, 'blue'), (12, 'violet')], default=0),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='crystal_colour_lustre',
            field=models.IntegerField(choices=[(0, 'not applicable'), (1, 'metallic'), (2, 'dull'), (3, 'clear')], default=0),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='crystal_colour_mod',
            field=models.IntegerField(choices=[(0, 'not applicable'), (1, 'light'), (2, 'dark'), (3, 'whitish'), (4, 'blackish'), (5, 'grayish'), (6, 'brownish'), (7, 'reddish'), (8, 'pinkish'), (9, 'orangish'), (10, 'yellowish'), (11, 'greenish'), (12, 'bluish')], default=0),
        ),
    ]
