# Generated by Django 2.1.4 on 2019-01-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['-number']},
        ),
        migrations.AddField(
            model_name='atom',
            name='xc',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atom',
            name='yc',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atom',
            name='zc',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
