# Generated by Django 2.1.5 on 2019-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciffile',
            name='refine_ls_hydrogen_treatment',
            field=models.CharField(blank=True, choices=[('undef', 'H-atom parameters not defined'), ('mixed', 'some constrained, some independent'), ('constr', 'H-atom parameters constrained'), ('noref', 'no refinement of H-atom parameters'), ('refall', 'refined all H-atom parameters'), ('refxyz', 'refined H-atom coordinates only'), ('refU', "refined H-atom U's only"), ('hetero', 'H-atom parameters constrained for H on C, all param. ref. on hetero H'), ('heteroxyz', 'H-atom parameters constrained for H on C, xyz ref. on hetero H'), ('heteroU', "H-atom parameters constrained for H on C, U's ref. on hetero H"), ('heteronoref', 'H-atom parameters constrained for H on C, no ref. on hetero H'), ('hetero-mixed', 'H-atom parameters constrained for H on C and some hetero, all param. ref. on hetero H'), ('heteroxyz-mixed', 'H-atom parameters constrained for H on C and some hetero, refined H coord. only for H on remaining heteroatoms'), ('heteroU-mixed', "H-atom parameters constrained for H on C and some heteroatoms, refined H-atom U's only for H on remaining heteroatoms"), ('heteronoref-mixed', 'H-atom parameters constrained for H on C and some heteroatoms, no refinement of H-atom parameters for H on remaining heteroatoms')], max_length=255, null=True),
        ),
    ]
