# Generated by Django 2.1.3 on 2018-12-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.IntegerField(default='Select Machine', verbose_name='machine used'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='solvents_used',
            field=models.IntegerField(verbose_name='solvents used'),
        ),
    ]
