# Generated by Django 2.1.3 on 2018-12-02 15:53

from django.db import migrations, models
import scxrd.models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0002_auto_20181202_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.IntegerField(choices=[(1, scxrd.models.Machine.__str__), (2, scxrd.models.Machine.__str__), (3, scxrd.models.Machine.__str__), (4, scxrd.models.Machine.__str__)], default='Select Machine', verbose_name='machine used'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='solvents_used',
            field=models.IntegerField(choices=[(1, scxrd.models.Solvent.__str__), (2, scxrd.models.Solvent.__str__), (3, scxrd.models.Solvent.__str__), (4, scxrd.models.Solvent.__str__), (5, scxrd.models.Solvent.__str__), (6, scxrd.models.Solvent.__str__)], verbose_name='solvents used'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=200, verbose_name='machines name'),
        ),
    ]
