# Generated by Django 2.1.5 on 2019-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0002_auto_20190107_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciffile',
            name='diffrn_reflns_av_R_equivalents',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
