# Generated by Django 2.1.5 on 2019-01-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0002_auto_20190117_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumformula',
            name='cif',
        ),
        migrations.AddField(
            model_name='ciffile',
            name='sumform',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cif_file', to='scxrd.SumFormula'),
        ),
    ]
