# Generated by Django 2.1.4 on 2019-01-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0002_auto_20190105_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atom',
            name='xc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='atom',
            name='yc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='atom',
            name='zc',
            field=models.FloatField(default=0),
        ),
    ]
