# Generated by Django 2.1.5 on 2019-01-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0003_auto_20190117_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciffile',
            old_name='sumform',
            new_name='sumform_calc',
        ),
    ]
