# Generated by Django 2.1.3 on 2018-12-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0003_auto_20181202_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.IntegerField(choices=[(1, 'APEX'), (2, 'Spider'), (3, 'Venture'), (4, 'Foobar')], verbose_name='machine used'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='solvents_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scxrd.Solvent', verbose_name='solvents used'),
        ),
    ]
