# Generated by Django 2.1.4 on 2018-12-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0003_experiment_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('checksum', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='applicaiton/binary', max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='scxrd/cifs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='cif',
        ),
    ]
