# Generated by Django 2.1.5 on 2019-01-15 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0004_auto_20190114_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='group_head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group', to='scxrd.Person'),
        ),
    ]
