# Generated by Django 2.1.5 on 2019-01-16 16:56

from django.db import migrations, models
import scxrd.cif_model


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0004_auto_20190116_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciffile',
            name='cif_file_on_disk',
            field=models.FileField(blank=True, null=True, upload_to='cifs', validators=[scxrd.cif_model.validate_file_extension], verbose_name='cif file name'),
        ),
    ]
