# Generated by Django 2.1.3 on 2018-12-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0004_auto_20181202_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='solvents_used',
            field=models.IntegerField(verbose_name='solvents used'),
        ),
        migrations.AlterField(
            model_name='solvent',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scxrd.Experiment', verbose_name='solvents name'),
        ),
    ]
