# Generated by Django 2.1.4 on 2018-12-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0004_auto_20181211_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
