# Generated by Django 2.1.3 on 2018-12-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0005_auto_20181202_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='solvents_used',
            field=models.CharField(max_length=200, verbose_name='solvents used'),
        ),
    ]
