# Generated by Django 2.1.5 on 2019-01-15 10:02

from django.db import migrations, models
import django.db.models.deletion
import scxrd.models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0005_auto_20190115_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='scxrd.Machine', verbose_name='diffractometer'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_adress',
            field=models.EmailField(blank=True, max_length=250, validators=[scxrd.models.validate_email]),
        ),
    ]
