# Generated by Django 2.1.5 on 2019-01-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0006_experiment_publishable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='publishable',
            field=models.BooleanField(default=False, verbose_name='structure is publishable'),
        ),
    ]
