# Generated by Django 2.1.3 on 2018-12-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0006_auto_20181202_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='solvents_used',
        ),
        migrations.AddField(
            model_name='experiment',
            name='solvents_used',
            field=models.ManyToManyField(blank=True, to='scxrd.Solvent', verbose_name='solvents used'),
        ),
        migrations.AlterField(
            model_name='solvent',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='solvents name'),
        ),
    ]
