# Generated by Django 2.1.4 on 2018-12-12 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0006_auto_20181212_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='category',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='name',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='size',
        ),
        migrations.AddField(
            model_name='experiment',
            name='cif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cif_file', to='scxrd.Upload', verbose_name='cif file'),
        ),
        migrations.AddField(
            model_name='upload',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to=settings.AUTH_USER_MODEL, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='cif',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cif_file_up', to='filer.File'),
        ),
    ]
