# Generated by Django 2.1.5 on 2019-01-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0006_auto_20190115_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='crystal_colour_lustre',
            field=models.IntegerField(blank=True, choices=[(0, 'not applicable'), (1, 'metallic'), (2, 'dull'), (3, 'clear')], default=0),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='crystal_colour_mod',
            field=models.IntegerField(blank=True, choices=[(0, 'not applicable'), (1, 'light'), (2, 'dark'), (3, 'whitish'), (4, 'blackish'), (5, 'grayish'), (6, 'brownish'), (7, 'reddish'), (8, 'pinkish'), (9, 'orangish'), (10, 'yellowish'), (11, 'greenish'), (12, 'bluish')], default=0),
        ),
    ]
