# Generated by Django 2.1.4 on 2018-12-12 09:07

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0007_auto_20181212_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='cif',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='cif',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cif_file_up', to='filer.File'),
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
