# Generated by Django 2.1.5 on 2019-01-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0007_auto_20190115_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciffile',
            name='shelx_res_file',
            field=models.TextField(blank=True, max_length=10000000, null=True),
        ),
    ]
