# Generated by Django 2.1.3 on 2018-12-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0008_auto_20181202_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sum_formula',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
