# Generated by Django 2.1.4 on 2018-12-12 09:14

from django.db import migrations
import filer.fields.multistorage_file


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0008_auto_20181212_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='cif',
            field=filer.fields.multistorage_file.MultiStorageFileField(blank=True, null=True, upload_to=filer.fields.multistorage_file.generate_filename_multistorage),
        ),
    ]
