# Generated by Django 2.1.5 on 2019-01-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0008_auto_20190115_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumformula',
            name='cif',
        ),
    ]
