# Generated by Django 2.1.3 on 2018-12-02 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scxrd', '0009_auto_20181202_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvent',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='experiment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
    ]
