# Generated by Django 2.1.5 on 2019-01-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0009_remove_sumformula_cif'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumformula',
            name='cif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scxrd.CifFile'),
        ),
    ]
