# Generated by Django 2.1.3 on 2018-12-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0010_auto_20181202_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.IntegerField(choices=[(1, 'APEX'), (2, 'Spider'), (3, 'Venture'), (4, 'Foobar')], verbose_name='diffractometer'),
        ),
    ]
