# Generated by Django 2.1.3 on 2018-12-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0012_auto_20181202_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.IntegerField(choices=[(1, 'APEX'), (2, 'VENTURE')], verbose_name='diffractometer'),
        ),
    ]
