# Generated by Django 2.1.3 on 2018-12-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0013_auto_20181203_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.IntegerField(verbose_name='diffractometer'),
        ),
    ]
