# Generated by Django 2.1.3 on 2018-12-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0017_fruit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
