# Generated by Django 2.1.3 on 2018-12-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0018_delete_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.IntegerField(choices=[(2, 'APEX'), (3, 'Spider'), (4, 'VENTURE')], verbose_name='diffractometer'),
        ),
    ]
