# Generated by Django 2.1.3 on 2018-12-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0022_auto_20181204_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='result_date',
            field=models.DateField(blank=True, default='2018-12-03', verbose_name='structure results date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiment',
            name='submit_date',
            field=models.DateField(blank=True, default='2018-12-03', verbose_name='sample submission date'),
            preserve_default=False,
        ),
    ]
