# Generated by Django 2.1.3 on 2018-12-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0023_auto_20181204_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='result_date',
            field=models.DateField(blank=True, null=True, verbose_name='structure results date'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='submit_date',
            field=models.DateField(blank=True, null=True, verbose_name='sample submission date'),
        ),
    ]
