# Generated by Django 2.1.3 on 2018-12-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0025_auto_20181205_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.IntegerField(choices=[(1, 'APEX'), (2, 'Spider'), (3, 'VENTURE')], verbose_name='diffractometer'),
        ),
    ]
