# Generated by Django 2.1.4 on 2018-12-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0027_auto_20181205_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', related_query_name='machine', to='scxrd.Machine', verbose_name='diffractometer'),
        ),
    ]
