# Generated by Django 2.1.4 on 2018-12-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0028_auto_20181205_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='scxrd.Machine', verbose_name='diffractometer'),
        ),
    ]
