# Generated by Django 2.1.4 on 2018-12-06 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scxrd', '0029_auto_20181205_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='measure_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='measurement date'),
        ),
    ]
