# Generated by Django 2.1.4 on 2018-12-07 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scxrd', '0030_auto_20181206_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='owner',
        ),
        migrations.AddField(
            model_name='experiment',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to=settings.AUTH_USER_MODEL, verbose_name='operator'),
            preserve_default=False,
        ),
    ]
