# Generated by Django 2.1.3 on 2018-12-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181202_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='question_text',
            new_name='machine_text',
        ),
    ]
