# Generated by Django 2.1.3 on 2018-12-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181202_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='machine_text',
            new_name='Machines name',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='machine_used',
            new_name='used_machine',
        ),
    ]
