# Generated by Django 2.1.3 on 2018-12-02 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181202_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='Machines name',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='experiment name',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='time of measurement',
        ),
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Machines name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time of measurement'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='experiment',
            field=models.CharField(default=2, max_length=200, verbose_name='experiment name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='used_machine',
            field=models.IntegerField(choices=[(1, 'Foo'), (2, 'Bar'), (3, 'APEX')]),
        ),
    ]
