# Generated by Django 2.1.5 on 2019-01-14 16:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='company')),
                ('street', models.CharField(blank=True, max_length=250)),
                ('house_number', models.CharField(blank=True, max_length=200)),
                ('building', models.CharField(blank=True, max_length=200)),
                ('town', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=200)),
                ('email_adress', models.EmailField(blank=True, max_length=250, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='myuser.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='work_group',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person', to='myuser.WorkGroup'),
        ),
    ]
